// Estilos compartilhados de telas e componentes. Extraído de App.tsx na
// refatoração da auditoria 2026-06-09 #12.1 — segue um StyleSheet único, como
// era no App.tsx; os componentes importam { styles } daqui.
import { StyleSheet } from 'react-native';

import { colors, radius, shadow, spacing, typography } from './theme';

export const styles = StyleSheet.create({
  appShell: {
    flex: 1,
    backgroundColor: colors.bg,
  },
  safeArea: {
    flex: 1,
  },
  screen: {
    flex: 1,
  },
  screenContent: {
    paddingHorizontal: spacing.screen,
    paddingTop: 18,
    gap: 14,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
  },
  headerText: {
    flex: 1,
  },
  eyebrowText: {
    ...typography.label,
    color: colors.ink3,
  },
  headerTitle: {
    ...typography.h1,
    color: colors.ink,
  },
  titleText: {
    ...typography.h2,
    color: colors.ink,
  },
  headerActions: {
    flexDirection: 'row',
    gap: 9,
  },
  rowCenter: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  iconButton: {
    width: 40,
    height: 40,
    borderRadius: 13,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.line,
    alignItems: 'center',
    justifyContent: 'center',
    ...shadow.small,
  },
  notificationBadge: {
    position: 'absolute',
    top: 8,
    right: 9,
    width: 8,
    height: 8,
    borderRadius: 8,
    backgroundColor: colors.coral,
    borderWidth: 1,
    borderColor: colors.surface,
  },
  activeCard: {
    backgroundColor: colors.surface,
    borderRadius: radius.card,
    borderWidth: 1,
    borderColor: colors.line2,
    padding: 18,
    ...shadow.small,
  },
  activeTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 14,
  },
  activeTitle: {
    ...typography.h2,
    color: colors.ink,
    marginTop: 9,
  },
  subtleText: {
    ...typography.bodySmall,
    color: colors.ink3,
  },
  ring: {
    width: 64,
    height: 64,
    borderRadius: 64,
    borderWidth: 8,
    borderColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surface,
  },
  ringText: {
    ...typography.labelStrong,
    color: colors.ink,
  },
  progressTrack: {
    height: 9,
    borderRadius: 9,
    backgroundColor: colors.bg2,
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    borderRadius: 9,
    backgroundColor: colors.primary,
  },
  activeFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 14,
  },
  estimateText: {
    ...typography.h3,
    color: colors.ink,
  },
  blackButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: colors.ink,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  blackButtonText: {
    ...typography.labelStrong,
    color: colors.surface,
  },
  statusPill: {
    alignSelf: 'flex-start',
    borderRadius: 9,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  statusPillText: {
    ...typography.badge,
  },
  quickActions: {
    flexDirection: 'row',
    gap: 9,
  },
  quickActionCard: {
    flex: 1,
    alignItems: 'center',
    gap: 7,
    backgroundColor: colors.surface,
    borderRadius: 17,
    borderWidth: 1,
    borderColor: colors.line2,
    paddingVertical: 13,
    ...shadow.small,
  },
  quickActionText: {
    ...typography.label,
    color: colors.ink2,
  },
  iconBubble: {
    borderRadius: 13,
    alignItems: 'center',
    justifyContent: 'center',
  },
  inventoryAlertCard: {
    backgroundColor: colors.surface,
    borderRadius: radius.card,
    borderWidth: 1,
    borderColor: colors.coralSoft,
    padding: 15,
    gap: 11,
    ...shadow.small,
  },
  inventoryAlertCardOk: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: colors.surface,
    borderRadius: radius.card,
    borderWidth: 1,
    borderColor: colors.primarySoft,
    padding: 14,
    ...shadow.small,
  },
  inventoryAlertHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
  },
  inventoryAlertLabel: {
    ...typography.badge,
    color: colors.coral,
    textTransform: 'uppercase',
  },
  inventoryAlertOkLabel: {
    ...typography.badge,
    color: colors.primaryStrong,
    textTransform: 'uppercase',
  },
  inventoryAlertTitle: {
    ...typography.labelStrong,
    color: colors.ink,
    marginTop: 2,
  },
  inventoryAlertAction: {
    borderRadius: 10,
    backgroundColor: colors.coralSoft,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  inventoryAlertActionText: {
    ...typography.badge,
    color: colors.coral,
  },
  inventoryAlertRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 9,
    borderTopWidth: 1,
    borderTopColor: colors.line2,
    paddingTop: 10,
  },
  inventoryAlertDot: {
    width: 9,
    height: 9,
    borderRadius: 9,
    backgroundColor: colors.amber,
  },
  inventoryAlertDotMissing: {
    backgroundColor: colors.coral,
  },
  inventoryAlertTextBlock: {
    flex: 1,
    minWidth: 0,
  },
  inventoryAlertItemName: {
    ...typography.labelStrong,
    color: colors.ink,
  },
  inventoryAlertBadge: {
    ...typography.badge,
    color: colors.amber,
    backgroundColor: colors.amberSoft,
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  inventoryAlertBadgeMissing: {
    color: colors.coral,
    backgroundColor: colors.coralSoft,
  },
  suggestionCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 13,
    backgroundColor: colors.surface,
    borderRadius: radius.card,
    borderWidth: 1,
    borderColor: colors.indigoSoft,
    padding: 14,
    ...shadow.small,
  },
  suggestionText: {
    flex: 1,
  },
  suggestionLabel: {
    ...typography.badge,
    color: colors.indigo,
    textTransform: 'uppercase',
  },
  suggestionTitle: {
    ...typography.labelStrong,
    color: colors.ink,
  },
  suggestionAdd: {
    width: 36,
    height: 36,
    borderRadius: 12,
    backgroundColor: colors.indigo,
    alignItems: 'center',
    justifyContent: 'center',
  },
  suggestionAddDisabled: {
    opacity: 0.45,
  },
  sectionTitle: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 2,
  },
  sectionTitleText: {
    ...typography.h3,
    color: colors.ink,
  },
  sectionAction: {
    ...typography.labelStrong,
    color: colors.primaryStrong,
  },
  productRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 13,
    backgroundColor: colors.surface,
    borderRadius: 17,
    borderWidth: 1,
    borderColor: colors.line2,
    paddingHorizontal: 13,
    paddingVertical: 11,
    ...shadow.small,
  },
  // Card principal de produto: coluna com [foto+texto] em cima e os botões de
  // ação numa linha própria embaixo, para o nome usar a largura toda.
  productCard: {
    flexDirection: 'column',
    gap: 11,
    backgroundColor: colors.surface,
    borderRadius: 17,
    borderWidth: 1,
    borderColor: colors.line2,
    paddingHorizontal: 13,
    paddingVertical: 11,
    ...shadow.small,
  },
  productHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 13,
  },
  productPhoto: {
    width: 44,
    height: 44,
    borderRadius: 13,
    backgroundColor: colors.bg2,
  },
  productText: {
    flex: 1,
    minWidth: 0,
  },
  productName: {
    ...typography.labelStrong,
    color: colors.ink,
  },
  productMeta: {
    ...typography.bodySmall,
    color: colors.ink3,
  },
  estoqueCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 11,
    backgroundColor: colors.surface,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.line2,
    paddingHorizontal: 11,
    paddingVertical: 8,
    ...shadow.small,
  },
  estoquePhoto: {
    width: 34,
    height: 34,
    borderRadius: 11,
    backgroundColor: colors.bg2,
  },
  inventoryControls: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 6,
    marginTop: 7,
  },
  inventoryQuantityPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    alignSelf: 'flex-start',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.bg,
    padding: 3,
  },
  inventoryMissingPill: {
    borderColor: colors.coralSoft,
    backgroundColor: colors.coralSoft,
  },
  inventoryMiniButton: {
    width: 44,
    height: 44,
    borderRadius: 8,
    backgroundColor: colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
  },
  inventoryQuantityText: {
    ...typography.badge,
    color: colors.ink,
    minWidth: 34,
    textAlign: 'center',
  },
  inventoryMissingButton: {
    alignSelf: 'flex-start',
    minHeight: 44,
    justifyContent: 'center',
    borderRadius: 9,
    backgroundColor: colors.bg2,
    paddingHorizontal: 8,
    paddingVertical: 5,
  },
  inventoryMissingButtonActive: {
    backgroundColor: colors.coralSoft,
  },
  inventoryMissingButtonText: {
    ...typography.badge,
    color: colors.ink2,
  },
  inventoryMissingButtonTextActive: {
    color: colors.coral,
  },
  inventoryConsumeButton: {
    alignSelf: 'flex-start',
    minHeight: 44,
    justifyContent: 'center',
    borderRadius: 9,
    backgroundColor: colors.primarySoft,
    paddingHorizontal: 9,
    paddingVertical: 5,
  },
  inventoryConsumeButtonDisabled: {
    opacity: 0.58,
  },
  inventoryConsumeButtonText: {
    ...typography.badge,
    color: colors.primaryStrong,
  },
  inventoryThresholdText: {
    ...typography.badge,
    alignSelf: 'center',
    color: colors.ink3,
  },
  productActions: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 6,
  },
  productActionButton: {
    width: 44,
    height: 44,
    borderRadius: 11,
    backgroundColor: colors.bg2,
    alignItems: 'center',
    justifyContent: 'center',
  },
  productDeleteButton: {
    backgroundColor: colors.coralSoft,
  },
  archivedToggle: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.line2,
    backgroundColor: colors.surface,
    marginBottom: 4,
  },
  archivedToggleActive: {
    backgroundColor: colors.ink,
    borderColor: colors.ink,
  },
  archivedToggleText: {
    ...typography.labelStrong,
    color: colors.ink2,
  },
  archivedToggleTextActive: {
    color: colors.surface,
  },
  unarchiveButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: 12,
    paddingVertical: 8,
    minHeight: 44,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.line2,
  },
  unarchiveText: {
    ...typography.labelStrong,
    color: colors.primaryStrong,
  },
  occasionalRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    minHeight: 44,
    paddingVertical: 4,
  },
  occasionalTextBlock: {
    flex: 1,
  },
  occasionalTitle: {
    ...typography.labelStrong,
    color: colors.ink,
  },
  occasionalHint: {
    ...typography.label,
    color: colors.ink3,
  },
  productNameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  productNameFlex: {
    // Deixa o nome encolher/quebrar dentro da linha (e ceder espaço ao badge),
    // em vez de truncar quando os botões de ação estreitam a coluna.
    flexShrink: 1,
  },
  eventualBadge: {
    ...typography.label,
    color: colors.ink2,
    backgroundColor: colors.bg2,
    borderRadius: 6,
    paddingHorizontal: 6,
    paddingVertical: 1,
    overflow: 'hidden',
  },
  productError: {
    ...typography.labelStrong,
    color: colors.coral,
    backgroundColor: colors.coralSoft,
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  addMini: {
    width: 44,
    height: 44,
    borderRadius: 11,
    backgroundColor: colors.primarySoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: colors.surface,
    borderRadius: radius.card,
    borderWidth: 1,
    borderColor: colors.line2,
    padding: 16,
    ...shadow.small,
  },
  emptyTextBlock: {
    flex: 1,
    gap: 2,
  },
  emptyTitle: {
    ...typography.labelStrong,
    color: colors.ink,
  },
  emptyDescription: {
    ...typography.bodySmall,
    color: colors.ink3,
  },
  searchBox: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: colors.surface,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: colors.line,
    paddingHorizontal: 14,
    paddingVertical: 13,
    ...shadow.small,
  },
  searchPlaceholder: {
    ...typography.body,
    color: colors.ink3,
  },
  searchInput: {
    flex: 1,
    ...typography.body,
    color: colors.ink,
    paddingVertical: 0,
  },
  chipRow: {
    gap: 8,
  },
  chip: {
    borderRadius: 100,
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.surface,
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  chipActive: {
    backgroundColor: colors.ink,
    borderColor: colors.ink,
  },
  chipText: {
    ...typography.labelStrong,
    color: colors.ink2,
  },
  chipTextActive: {
    color: colors.surface,
  },
  listHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  listTitleBlock: {
    marginLeft: 10,
  },
  categoryHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 16,
    marginBottom: 9,
  },
  categoryDot: {
    width: 8,
    height: 8,
    borderRadius: 8,
  },
  categoryTitle: {
    ...typography.labelStrong,
    color: colors.ink2,
    flex: 1,
  },
  categoryCount: {
    ...typography.label,
    color: colors.ink3,
  },
  shoppingItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: colors.surface,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.line2,
    paddingHorizontal: 13,
    paddingVertical: 11,
    marginBottom: 7,
    ...shadow.small,
  },
  shoppingItemToggle: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    minWidth: 0,
  },
  checkBox: {
    width: 26,
    height: 26,
    borderRadius: 9,
    borderWidth: 2,
    borderColor: colors.line,
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkBoxDone: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  shoppingItemText: {
    flex: 1,
  },
  checkedText: {
    color: colors.ink3,
    textDecorationLine: 'line-through',
  },
  quantityPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
    backgroundColor: colors.bg,
    borderRadius: 11,
    borderWidth: 1,
    borderColor: colors.line,
    padding: 4,
  },
  qtyButton: {
    width: 24,
    height: 24,
    borderRadius: 8,
    backgroundColor: colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
  },
  quantityText: {
    ...typography.labelStrong,
    color: colors.ink,
    minWidth: 40,
    textAlign: 'center',
  },
  removeItemButton: {
    width: 32,
    height: 32,
    borderRadius: 11,
    backgroundColor: colors.coralSoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  missingBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    gap: 4,
    marginTop: 4,
    backgroundColor: colors.coralSoft,
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  missingText: {
    ...typography.badge,
    color: colors.coral,
  },
  historyGroupTitle: {
    ...typography.labelStrong,
    color: colors.ink3,
    marginTop: 8,
    marginBottom: 8,
  },
  historyCard: {
    backgroundColor: colors.surface,
    borderRadius: radius.card,
    borderWidth: 1,
    borderColor: colors.line2,
    padding: 14,
    marginBottom: 9,
    ...shadow.small,
  },
  historyCardTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  historyTopRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  historyTitle: {
    ...typography.h3,
    color: colors.ink,
  },
  historyTotal: {
    ...typography.h3,
    color: colors.primaryStrong,
  },
  purchaseLinesScroll: {
    maxHeight: 360,
  },
  purchaseLines: {
    gap: 2,
  },
  purchaseLine: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: colors.line2,
  },
  purchaseLineName: {
    ...typography.body,
    color: colors.ink,
    flex: 1,
  },
  purchaseLineQty: {
    ...typography.labelStrong,
    color: colors.ink2,
  },
  historyMetaRow: {
    flexDirection: 'row',
    gap: 12,
  },
  metaLabel: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  metaLabelText: {
    ...typography.label,
    color: colors.ink3,
  },
  thumbRow: {
    flexDirection: 'row',
    gap: 6,
    marginTop: 11,
  },
  moreThumb: {
    width: 34,
    height: 34,
    borderRadius: 11,
    backgroundColor: colors.bg2,
    alignItems: 'center',
    justifyContent: 'center',
  },
  moreText: {
    ...typography.labelStrong,
    color: colors.ink2,
  },
  futureHero: {
    backgroundColor: colors.ink,
    borderRadius: radius.card,
    padding: 22,
    gap: 12,
  },
  futureHeroTitle: {
    ...typography.h2,
    color: colors.surface,
  },
  futureHeroText: {
    ...typography.body,
    color: 'rgba(255,255,255,0.72)',
  },
  bottomShell: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'transparent',
    paddingHorizontal: 16,
    paddingTop: 10,
  },
  bottomBar: {
    height: 68,
    borderRadius: 22,
    backgroundColor: 'rgba(255,255,255,0.94)',
    borderWidth: 1,
    borderColor: colors.line,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    ...shadow.medium,
  },
  tabButton: {
    width: 58,
    alignItems: 'center',
    gap: 3,
    paddingVertical: 7,
  },
  tabLabel: {
    fontSize: 10,
    fontWeight: '700',
    color: colors.ink3,
  },
  tabLabelActive: {
    color: colors.primaryStrong,
  },
  fab: {
    width: 54,
    height: 54,
    borderRadius: 18,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: -28,
    ...shadow.medium,
  },
  finalizeShell: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: colors.bg,
    paddingHorizontal: 16,
    paddingTop: 10,
  },
  estimateRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 4,
    paddingBottom: 8,
  },
  estimateLabel: {
    ...typography.labelStrong,
    color: colors.ink2,
  },
  estimateHint: {
    ...typography.label,
    color: colors.ink3,
  },
  estimateValue: {
    ...typography.h2,
    color: colors.primaryStrong,
  },
  finalizeButton: {
    height: 58,
    borderRadius: 18,
    backgroundColor: colors.primary,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    ...shadow.medium,
  },
  finalizeButtonDisabled: {
    opacity: 0.55,
  },
  finalizeText: {
    ...typography.labelStrong,
    color: colors.surface,
    fontSize: 16,
  },
  sheetKeyboardWrap: {
    flex: 1,
  },
  modalScrim: {
    flex: 1,
    backgroundColor: 'rgba(33,36,24,0.32)',
  },
  sheetShell: {
    backgroundColor: colors.surface,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    paddingHorizontal: spacing.screen,
    paddingTop: 10,
    paddingBottom: 18,
    gap: 12,
  },
  // Sheet com formulário longo: encolhe quando o teclado abre (o conteúdo
  // rola via ScrollView com sheetScrollContent).
  sheetShellShrink: {
    flexShrink: 1,
  },
  sheetScrollContent: {
    gap: 12,
  },
  sheetHandle: {
    alignSelf: 'center',
    width: 44,
    height: 5,
    borderRadius: 5,
    backgroundColor: colors.line,
    marginBottom: 4,
  },
  sheetTitle: {
    ...typography.h2,
    color: colors.ink,
  },
  sheetSubtitle: {
    ...typography.body,
    color: colors.ink3,
  },
  fieldLabel: {
    ...typography.labelStrong,
    color: colors.ink2,
  },
  inputBox: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    minHeight: 52,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: colors.primary,
    backgroundColor: colors.surface,
    paddingHorizontal: 14,
  },
  input: {
    flex: 1,
    ...typography.body,
    color: colors.ink,
    paddingVertical: 0,
  },
  formError: {
    ...typography.label,
    color: colors.coral,
    marginTop: -6,
  },
  optionalRow: {
    flexDirection: 'row',
    gap: 10,
  },
  optionalCapture: {
    flex: 1,
    alignItems: 'center',
    gap: 7,
    borderRadius: 15,
    borderWidth: 1.5,
    borderStyle: 'dashed',
    borderColor: colors.line,
    padding: 14,
  },
  optionalText: {
    ...typography.label,
    color: colors.ink3,
  },
  sheetPhotoPreview: {
    width: '100%',
    height: 140,
    borderRadius: 16,
    backgroundColor: colors.bg2,
  },
  captureResult: {
    ...typography.label,
    color: colors.ink2,
    backgroundColor: colors.bg2,
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  scannerShell: {
    flex: 1,
    backgroundColor: colors.ink,
  },
  scannerHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 16,
    paddingHorizontal: spacing.screen,
    paddingVertical: 16,
  },
  scannerTitle: {
    ...typography.h2,
    color: colors.surface,
  },
  scannerSubtitle: {
    ...typography.bodySmall,
    color: 'rgba(255,255,255,0.68)',
  },
  scannerClose: {
    width: 44,
    height: 44,
    borderRadius: 14,
    backgroundColor: 'rgba(255,255,255,0.14)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  scannerCamera: {
    flex: 1,
  },
  scannerHint: {
    ...typography.label,
    color: 'rgba(255,255,255,0.72)',
    textAlign: 'center',
    paddingHorizontal: spacing.screen,
    paddingVertical: 16,
  },
  scannerRetryButton: {
    marginHorizontal: spacing.screen,
    marginBottom: 16,
  },
  photoCaptureBar: {
    alignItems: 'center',
    paddingTop: 18,
    backgroundColor: colors.ink,
  },
  photoCaptureButton: {
    width: 74,
    height: 74,
    borderRadius: 74,
    borderWidth: 4,
    borderColor: colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
  },
  photoCaptureButtonInner: {
    width: 54,
    height: 54,
    borderRadius: 54,
    backgroundColor: colors.surface,
  },
  saveButton: {
    height: 54,
    borderRadius: 16,
    backgroundColor: colors.primary,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  saveButtonDisabled: {
    opacity: 0.72,
  },
  saveButtonText: {
    ...typography.labelStrong,
    color: colors.surface,
  },
  syncCard: {
    gap: 12,
    backgroundColor: colors.surface,
    borderRadius: radius.card,
    borderWidth: 1,
    borderColor: colors.indigoSoft,
    padding: 16,
    ...shadow.small,
  },
  syncHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 13,
  },
  syncHeaderText: {
    flex: 1,
    gap: 3,
  },
  syncTitle: {
    ...typography.h3,
    color: colors.ink,
  },
  syncPairedRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderRadius: 12,
    backgroundColor: colors.indigoSoft,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  syncPairedLabel: {
    ...typography.labelStrong,
    color: colors.ink2,
  },
  syncPairedCode: {
    ...typography.labelStrong,
    color: colors.indigo,
    letterSpacing: 2,
  },
  syncUnpairButton: {
    alignItems: 'center',
    paddingVertical: 6,
  },
  syncUnpairText: {
    ...typography.label,
    color: colors.coral,
  },
  syncMessageOk: {
    ...typography.label,
    color: colors.primaryStrong,
  },
  syncDivider: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginVertical: 2,
  },
  syncDividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: colors.line,
  },
  syncDividerText: {
    ...typography.label,
    color: colors.ink3,
  },
  syncConnectText: {
    ...typography.labelStrong,
    color: colors.indigo,
  },
  priceLine: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    marginTop: 4,
  },
  priceLast: {
    ...typography.labelStrong,
    color: colors.ink,
  },
  priceRange: {
    ...typography.label,
    color: colors.ink3,
  },
  purchaseHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  purchaseEditButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingVertical: 4,
    paddingHorizontal: 8,
    minHeight: 44,
  },
  purchaseEditButtonText: {
    ...typography.labelStrong,
    color: colors.primaryStrong,
  },
  purchaseLineRemove: {
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
  },
  purchaseAddButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 12,
    borderRadius: radius.card,
    borderWidth: 1,
    borderColor: colors.primary,
    borderStyle: 'dashed',
    marginTop: 8,
  },
  purchaseAddButtonText: {
    ...typography.labelStrong,
    color: colors.primaryStrong,
  },
  purchaseProductPickerItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 12,
    minHeight: 44,
    borderBottomWidth: 1,
    borderBottomColor: colors.line2,
  },
  purchaseProductPickerName: {
    ...typography.body,
    color: colors.ink,
    flex: 1,
  },
  purchaseProductPickerMeta: {
    ...typography.label,
    color: colors.ink3,
  },
  purchaseSearchBox: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    minHeight: 44,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.surface,
    paddingHorizontal: 12,
    marginBottom: 8,
  },
  purchaseSearchInput: {
    flex: 1,
    ...typography.body,
    color: colors.ink,
    paddingVertical: 0,
  },
});
